## Overview / Cheat Sheet of Working with Tensors

In [1]:
import torch
import numpy as np

In [2]:
x = [
    [1, 2, 3],
    [10, 20, 30],
    [12, 13, 14]
]

In [3]:
print(x[0])
print(x[0][1])
print(x[2][1])

[1, 2, 3]
2
13


In [4]:
x_tensor = torch.tensor(x)
print(x_tensor)

tensor([[ 1,  2,  3],
        [10, 20, 30],
        [12, 13, 14]])


In [5]:
type(x_tensor)

torch.Tensor

In [6]:
x_tensor.dtype

torch.int64

#### The Tensors shape gives information on the rank and length of axis. Rank = Number of Axis

In [7]:
x_tensor.shape #is a tuple, so tuple operations are supported

torch.Size([3, 3])

### Shape is the same as Size:

In [9]:
x_tensor.size() #is a tuple, so tuple operations are supported

torch.Size([3, 3])

In [10]:
len(x_tensor.shape) #Rank

2

In [28]:
x_shp = x_tensor.reshape(1, 9)
print(x_shp)

tensor([[ 1,  2,  3, 10, 20, 30, 12, 13, 14]])


In [8]:
x_shp.shape

torch.Size([1, 9])

In [29]:
len(x_shp.shape)

2

### Tensor Operation Types

#### Reshaping Operations

In [12]:
t = torch.rand(3, 4, dtype = torch.float)
print(t)

tensor([[0.0725, 0.9235, 0.1113, 0.9456],
        [0.3632, 0.4313, 0.4027, 0.2968],
        [0.9170, 0.4829, 0.5709, 0.7110]])


In [13]:
len(t.shape) #rank of the tensor

2

In [14]:
torch.tensor(t.shape).prod() #number of items by calculating the product of the "matrix"

tensor(12)

In [15]:
t.numel() #same outcome (numel = number of elements), important because when reshaping always must entail 12items

12

In [16]:
t.reshape(2, 6)

tensor([[0.0725, 0.9235, 0.1113, 0.9456, 0.3632, 0.4313],
        [0.4027, 0.2968, 0.9170, 0.4829, 0.5709, 0.7110]])

In [17]:
t.reshape(4, 3)

tensor([[0.0725, 0.9235, 0.1113],
        [0.9456, 0.3632, 0.4313],
        [0.4027, 0.2968, 0.9170],
        [0.4829, 0.5709, 0.7110]])

In [18]:
t.reshape(2, 2, 3) #making it rank 3

tensor([[[0.0725, 0.9235, 0.1113],
         [0.9456, 0.3632, 0.4313]],

        [[0.4027, 0.2968, 0.9170],
         [0.4829, 0.5709, 0.7110]]])

In [21]:
#Squeezing a tensor
print(t.reshape(1, 12).squeeze())
t.reshape(1, 12).squeeze().shape

tensor([0.0725, 0.9235, 0.1113, 0.9456, 0.3632, 0.4313, 0.4027, 0.2968, 0.9170,
        0.4829, 0.5709, 0.7110])


torch.Size([12])

In [72]:
#Unsqueezing a tensor
print(t.unsqueeze(dim = 0))
t.unsqueeze(dim = 0).shape

tensor([[[0.0140, 0.5568, 0.3796, 0.8093],
         [0.5503, 0.4787, 0.6533, 0.2249],
         [0.4249, 0.2971, 0.0021, 0.0056]]])


torch.Size([1, 3, 4])

In [25]:
#Squeezing is implemented in the flatten function, which is needed from CNN to FC, demonstrated here:
def flatten(t):
    t = t.reshape(1, -1) #minus one tells to figure out how many columns basically
    t = t.squeeze()
    return t

flatten(t)

tensor([0.0725, 0.9235, 0.1113, 0.9456, 0.3632, 0.4313, 0.4027, 0.2968, 0.9170,
        0.4829, 0.5709, 0.7110])

In [26]:
#What happens without squeezing:
t.reshape(1, -1) #double [[

tensor([[0.0725, 0.9235, 0.1113, 0.9456, 0.3632, 0.4313, 0.4027, 0.2968, 0.9170,
         0.4829, 0.5709, 0.7110]])

In [27]:
#Concatenation:
t1 = torch.rand(2, 2, dtype = torch.float)
t2 = torch.rand(2, 2, dtype = torch.float)
print(t1, "\n", t2)

tensor([[0.0872, 0.1423],
        [0.7589, 0.7938]]) 
 tensor([[0.1768, 0.4992],
        [0.2474, 0.1816]])


In [28]:
torch.cat((t1, t2), dim = 0) #dim 0 concatenats "row-wise"

tensor([[0.0872, 0.1423],
        [0.7589, 0.7938],
        [0.1768, 0.4992],
        [0.2474, 0.1816]])

In [29]:
torch.cat((t1, t2), dim = 1) #dim 1 concatenates "column-wise"

tensor([[0.0872, 0.1423, 0.1768, 0.4992],
        [0.7589, 0.7938, 0.2474, 0.1816]])

#### Element-Wise / Component-Wise / Point-Wise Operations

In [94]:
# = works on corresponding elements between tensors
# elements are corresponding, when two elements occupy the same position within the tensor (determined by the index)
# Pre-requesite: They must have the same shape

In [30]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print(t1, "\n", t2)

tensor([[0.3021, 0.4292],
        [0.1821, 0.8664]]) 
 tensor([[0.4398, 0.8100],
        [0.6305, 0.8748]])


In [31]:
t1[0][0] #corresponding elements with t2

tensor(0.3021)

In [32]:
t2[0][0]

tensor(0.4398)

In [33]:
#Addition for example is element-wise
t1 + t2

tensor([[0.7420, 1.2391],
        [0.8126, 1.7412]])

In [34]:
#works with scalars as well
t1.div(2)
#but does not have the same shape??

tensor([[0.1511, 0.2146],
        [0.0911, 0.4332]])

In [35]:
#Therefore, tensor broadcasting is a concept:
b_2 = np.broadcast_to(2, t1.shape)
b_2

array([[2, 2],
       [2, 2]])

In [37]:
t1.div(torch.tensor(b_2))

tensor([[0.1511, 0.2146],
        [0.0911, 0.4332]])

In [38]:
#this also works with other rank tensors:
t3 = torch.rand(1, 2)
t3

tensor([[0.1622, 0.7674]])

In [39]:
t1 + t3 #totally works

tensor([[0.4643, 1.1966],
        [0.3443, 1.6338]])

In [40]:
#works also with other operations
t3.ge(0) #greater or equal; eq, gt, lt, le

tensor([[True, True]])

In [41]:
t3.abs() #absolute; sqrt(), neg()

tensor([[0.1622, 0.7674]])

#### Reduction Operations

In [42]:
# = reducing the number of elements contained in the tensor
# = operations in one tensor
t = torch.rand(3, 3)
t

tensor([[0.7352, 0.6705, 0.7115],
        [0.4169, 0.9530, 0.7386],
        [0.1368, 0.3029, 0.4437]])

In [43]:
t.sum()

tensor(5.1091)

In [44]:
t.numel() #number of elements

9

In [45]:
t.sum().numel() #sum() operation reduced number of elements

1

In [46]:
t.prod()

tensor(0.0019)

In [47]:
t.mean()

tensor(0.5677)

In [48]:
t.std()

tensor(0.2576)

In [49]:
t.median()

tensor(0.6705)

In [50]:
#but they not only reduce to a single element...
# can be done to a specific axis (dim parameter)
t = torch.rand(3, 4)
t

tensor([[0.9438, 0.0715, 0.7528, 0.7729],
        [0.9509, 0.2822, 0.6651, 0.8210],
        [0.2747, 0.0096, 0.9600, 0.0093]])

In [51]:
t.sum(dim = 0) #calculates sum for each "column": summing the elements of the first axis

tensor([2.1695, 0.3633, 2.3779, 1.6032])

In [52]:
t.sum(dim = 1) #calculates sum for each "row": summing the elements of the second axis

tensor([2.5410, 2.7192, 1.2536])

#### Access Operations

In [53]:
#ARGMAX function
# often used on prediction, to see which category has highest probability
t = torch.rand(3, 4)
t

tensor([[0.6371, 0.1362, 0.0656, 0.2590],
        [0.2410, 0.8606, 0.2350, 0.2104],
        [0.8663, 0.3234, 0.6729, 0.4321]])

In [54]:
t.argmax() #index 9

tensor(8)

In [55]:
t.argmax(dim = 0) #gives the index for the highest number for every "column"

tensor([2, 1, 2, 2])

In [56]:
t.argmax(dim = 1) #gives index for the highes number for every "row"

tensor([0, 1, 0])

In [57]:
#ACCESSING ITEMS IN TENSOR
t.max().item() #gives back a number and not a tensor
# but works only for scalar tensors

0.8662646412849426

In [58]:
t.tolist()

[[0.6371443867683411,
  0.13622546195983887,
  0.06560784578323364,
  0.25895363092422485],
 [0.24103528261184692,
  0.8605844378471375,
  0.23499321937561035,
  0.21044772863388062],
 [0.8662646412849426,
  0.32339704036712646,
  0.6728999018669128,
  0.43214744329452515]]

In [59]:
t.numpy() #convert to numpy array

array([[0.6371444 , 0.13622546, 0.06560785, 0.25895363],
       [0.24103528, 0.86058444, 0.23499322, 0.21044773],
       [0.86626464, 0.32339704, 0.6728999 , 0.43214744]], dtype=float32)