#### PyTorch only takes batches of pictures for training (in the format batchsize, colorchannel, height, width), which sometimes requires operations on them beforehand. As an example, those three Tensors represent three pictures 4x4. Those three Tensors must be combined to one, as a batch is one Tensor only.

In [2]:
import torch

In [3]:
t1 = torch.rand(4, 4)
t2 = torch.rand(4, 4)
t3 = torch.rand(4, 4)
print(t1, "\n", t2, "\n", t3)

tensor([[0.2248, 0.6739, 0.0654, 0.9750],
        [0.0515, 0.1576, 0.7053, 0.6500],
        [0.3019, 0.1109, 0.7773, 0.1881],
        [0.6008, 0.5648, 0.3179, 0.4180]]) 
 tensor([[0.8730, 0.2742, 0.3613, 0.2737],
        [0.0917, 0.2331, 0.5329, 0.2045],
        [0.9011, 0.1356, 0.9671, 0.5750],
        [0.2757, 0.1584, 0.1826, 0.2419]]) 
 tensor([[0.7059, 0.2426, 0.1750, 0.6246],
        [0.7348, 0.7865, 0.0702, 0.7750],
        [0.9697, 0.7059, 0.8368, 0.1521],
        [0.9095, 0.3953, 0.5696, 0.8009]])


In [4]:
#The stack function stacks all three tensors:
t = torch.stack((t1, t2, t3))
t

tensor([[[0.2248, 0.6739, 0.0654, 0.9750],
         [0.0515, 0.1576, 0.7053, 0.6500],
         [0.3019, 0.1109, 0.7773, 0.1881],
         [0.6008, 0.5648, 0.3179, 0.4180]],

        [[0.8730, 0.2742, 0.3613, 0.2737],
         [0.0917, 0.2331, 0.5329, 0.2045],
         [0.9011, 0.1356, 0.9671, 0.5750],
         [0.2757, 0.1584, 0.1826, 0.2419]],

        [[0.7059, 0.2426, 0.1750, 0.6246],
         [0.7348, 0.7865, 0.0702, 0.7750],
         [0.9697, 0.7059, 0.8368, 0.1521],
         [0.9095, 0.3953, 0.5696, 0.8009]]])

In [5]:
#Batchsize, height, width
# colorchannel is missing, we need to insert that
t.shape

torch.Size([3, 4, 4])

In [6]:
#inserting color channel
t = t.reshape(3, 1, 4, 4)
t

tensor([[[[0.2248, 0.6739, 0.0654, 0.9750],
          [0.0515, 0.1576, 0.7053, 0.6500],
          [0.3019, 0.1109, 0.7773, 0.1881],
          [0.6008, 0.5648, 0.3179, 0.4180]]],


        [[[0.8730, 0.2742, 0.3613, 0.2737],
          [0.0917, 0.2331, 0.5329, 0.2045],
          [0.9011, 0.1356, 0.9671, 0.5750],
          [0.2757, 0.1584, 0.1826, 0.2419]]],


        [[[0.7059, 0.2426, 0.1750, 0.6246],
          [0.7348, 0.7865, 0.0702, 0.7750],
          [0.9697, 0.7059, 0.8368, 0.1521],
          [0.9095, 0.3953, 0.5696, 0.8009]]]])

In [7]:
#The first image in the batch:
t[0]
#The first colorchannel of the first image:
t[0][0]
#The first row of pixels in the first colorchannel of the first image:
t[0][0][0]
#The first pixel value of the first pixel row in the first colorchannel of the first image:
t[0][0][0][0]

tensor(0.2248)

In [8]:
#How to flatten the image tensor now?
#Solution: Flattening each image while keeping the batch Tensor
f = t.flatten(start_dim = 1) #start_dim tells with which Tensor to start with to flatten the axis (colorchannel),
                                # batch axis is skipped so to say
print(f, "\n", f.shape)

tensor([[0.2248, 0.6739, 0.0654, 0.9750, 0.0515, 0.1576, 0.7053, 0.6500, 0.3019,
         0.1109, 0.7773, 0.1881, 0.6008, 0.5648, 0.3179, 0.4180],
        [0.8730, 0.2742, 0.3613, 0.2737, 0.0917, 0.2331, 0.5329, 0.2045, 0.9011,
         0.1356, 0.9671, 0.5750, 0.2757, 0.1584, 0.1826, 0.2419],
        [0.7059, 0.2426, 0.1750, 0.6246, 0.7348, 0.7865, 0.0702, 0.7750, 0.9697,
         0.7059, 0.8368, 0.1521, 0.9095, 0.3953, 0.5696, 0.8009]]) 
 torch.Size([3, 16])


In [9]:
#same with reshape:
g = t.reshape(t.shape[0], -1)
g

tensor([[0.2248, 0.6739, 0.0654, 0.9750, 0.0515, 0.1576, 0.7053, 0.6500, 0.3019,
         0.1109, 0.7773, 0.1881, 0.6008, 0.5648, 0.3179, 0.4180],
        [0.8730, 0.2742, 0.3613, 0.2737, 0.0917, 0.2331, 0.5329, 0.2045, 0.9011,
         0.1356, 0.9671, 0.5750, 0.2757, 0.1584, 0.1826, 0.2419],
        [0.7059, 0.2426, 0.1750, 0.6246, 0.7348, 0.7865, 0.0702, 0.7750, 0.9697,
         0.7059, 0.8368, 0.1521, 0.9095, 0.3953, 0.5696, 0.8009]])

#### What to do, when we have RGB images?
For RGB images, the colorchannels line up in one axis, so get flattened as well.